version: '3'

services:
  app:
    container_name: app
    build:
      context: ./app
      args:
        - PHP_VERSION=${PHP_VERSION}
        - APP_CONTAINER_PATH=${APP_CONTAINER_PATH}
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
    volumes:
      - ..:${APP_CONTAINER_PATH}
      # uncomment after container created & rebuild container again
      - ./logs/app:${APP_CONTAINER_PATH}/${APP_NAME}/storage/logs
      - ./logs/xdebug:${APP_CONTAINER_PATH}/${APP_NAME}/storage/logs
    environment:
      LARAVEL_SAIL: 1
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=172.120.19.9}
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    depends_on:
      - db
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        - APP_NAME=${APP_NAME}
        - APP_CONTAINER_PATH=${APP_CONTAINER_PATH}
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ..:${APP_CONTAINER_PATH}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app

  db:
    container_name: db
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./logs/db:/var/log/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"

  node:
    build:
      context: ./node
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NODE_APP_CONTAINER_PATH=${NODE_APP_CONTAINER_PATH}
    tty: true
    volumes:
      - ..:${NODE_APP_CONTAINER_PATH}
    ports:
      - ${NODE_PORT}:80

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - ${PHPMA_PORT}:80
    environment:
      - PMA_HOST=db